
- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://127.0.0.1:3080"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create a new GNS3 project
      uri:
        url: "{{ gns3_url }}/v2/projects"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "d1.drawio"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: project_result

    - name: Debug project creation result
      debug:
        var: project_result

    - name: Add 10700 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "10700",
            "x": 100,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "a53ede8e-b641-42c6-96a8-8aaab4dde3d9",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-N3248TE-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug 10700 creation result
      debug:
        var: machine_result

    - name: Add 10700 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "10700",
            "x": 150,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "a53ede8e-b641-42c6-96a8-8aaab4dde3d9",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-N3248TE-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug 10700 creation result
      debug:
        var: machine_result

    - name: Add 10700 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "10700",
            "x": 200,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "a53ede8e-b641-42c6-96a8-8aaab4dde3d9",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-N3248TE-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug 10700 creation result
      debug:
        var: machine_result

    - name: Add 10700 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "10700",
            "x": 250,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "a53ede8e-b641-42c6-96a8-8aaab4dde3d9",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-N3248TE-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug 10700 creation result
      debug:
        var: machine_result

    - name: Add atm_switch to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "atm_switch",
            "x": 100,
            "y": 150,
            "compute_id": "local",
            "node_type": "ethernet_switch",
            "symbol": ":/symbols/ethernet_switch.svg",
            "template_id": "1966b864-93e7-32d5-965f-001384eec461"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug atm_switch creation result
      debug:
        var: machine_result

    - name: Add atm_switch to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "atm_switch",
            "x": 150,
            "y": 150,
            "compute_id": "local",
            "node_type": "ethernet_switch",
            "symbol": ":/symbols/ethernet_switch.svg",
            "template_id": "1966b864-93e7-32d5-965f-001384eec461"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug atm_switch creation result
      debug:
        var: machine_result

    - name: Add atm_switch to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "atm_switch",
            "x": 200,
            "y": 150,
            "compute_id": "local",
            "node_type": "ethernet_switch",
            "symbol": ":/symbols/ethernet_switch.svg",
            "template_id": "1966b864-93e7-32d5-965f-001384eec461"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug atm_switch creation result
      debug:
        var: machine_result

    - name: Add atm_switch to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "atm_switch",
            "x": 250,
            "y": 150,
            "compute_id": "local",
            "node_type": "ethernet_switch",
            "symbol": ":/symbols/ethernet_switch.svg",
            "template_id": "1966b864-93e7-32d5-965f-001384eec461"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug atm_switch creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 100,
            "y": 200,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 150,
            "y": 200,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 200,
            "y": 200,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 250,
            "y": 200,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 100,
            "y": 250,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 150,
            "y": 250,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 200,
            "y": 250,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result

    - name: Add pc to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "pc",
            "x": 250,
            "y": 250,
            "compute_id": "local",
            "node_type": "vpcs",
            "symbol": ":/symbols/vpcs_guest.svg",
            "template_id": "19021f99-e36f-394d-b4a1-8aaa902ab9cc"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug pc creation result
      debug:
        var: machine_result
