
- hosts: localhost
  gather_facts: no
  vars:
    gns3_url: "http://127.0.0.1:3080"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create a new GNS3 project
      uri:
        url: "{{ gns3_url }}/v2/projects"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "Final_Testing"
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: project_result

    - name: Debug project creation result
      debug:
        var: project_result

    - name: Add N3248TE-ONFrontView88 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "N3248TE-ONFrontView88",
            "x": 100,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "a53ede8e-b641-42c6-96a8-8aaab4dde3d9",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-N3248TE-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug N3248TE-ONFrontView88 creation result
      debug:
        var: machine_result

    - name: Add S4128F-ONFrontView94 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "S4128F-ONFrontView94",
            "x": 150,
            "y": 100,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "4a894368-bd42-4eb6-802d-904896b74a06",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-S4128F-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/usr/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug S4128F-ONFrontView94 creation result
      debug:
        var: machine_result

    - name: Add S5212F-ONFrontView(ACPower)72 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "S5212F-ONFrontView(ACPower)72",
            "x": 100,
            "y": 150,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "f0290fc2-d213-4192-b32d-6aa0969ebbc0",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-S5212F-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/usr/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug S5212F-ONFrontView(ACPower)72 creation result
      debug:
        var: machine_result

    - name: Add S5224F-ONFrontView75 to the project
      uri:
        url: "{{ gns3_url }}/v2/projects/{{ project_result.json.project_id }}/nodes"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "S5224F-ONFrontView75",
            "x": 150,
            "y": 150,
            "compute_id": "local",
            "node_type": "qemu",
            "symbol": ":/symbols/router.svg",
            "template_id": "362bd958-525c-4b3e-b08e-6d8f497e0579",
            "first_port_name": "mgmt 1/1/1",
            "port_name_format": "eth 1/1/{port1}",
            "properties": {
              "adapter_type": "e1000",
              "adapters": 10,
              "console_type": "telnet",
              "cpus": 1,
              "hda_disk_image": "OS10-Disk-1.0.0.vmdk",
              "hda_disk_interface": "sata",
              "hdb_disk_image": "OS10-Installer-10.5.5.5.105.vmdk",
              "hdb_disk_interface": "virtio",
              "hdc_disk_image": "OS10-platform-S5224F-10.5.5.5.105.vmdk",
              "hdc_disk_interface": "virtio",
              "ram": 4096,
              "boot_priority": "d",
              "qemu_path": "/usr/bin/qemu-system-x86_64",
              "replicate_network_connection_state": true
            }
          }
        body_format: json
        return_content: yes
        status_code: 201
      register: machine_result

    - name: Debug S5224F-ONFrontView75 creation result
      debug:
        var: machine_result
